### ISSUE TITLE
Error when trying to compile ELL

### ISSUE THREAD

**Issue by jesuspicazo** [Microsoft/ELL#151] opened 2018-05-16 09:39 UTC
Hi,
When trying to compile ELL in Ubuntu 16.04, I get the following error:
/home/icai23/ELL/libraries/dsp/src/WinogradConvolution.cpp:194:15: error: array must be initialized with a brace-enclosed initializer
         class Fixed3DArray

This never happened with older versions and I don't know whether I'm doing anything wrong.

Thank you very much.

Best regards.

Jesus.

**Comment by lovettchris** [comment] 2018-06-12 20:20
Duplicate of [https://github.com/Microsoft/ELL/issues/157](https://github.com/Microsoft/ELL/issues/157) which has more discussion.

**Closed by lovettchris** 2018-06-12 20:20 UTC
